"""Verificar longitud de columnas

Revision ID: 224e010e8eca
Revises: 2f348a93d2cf
Create Date: 2024-07-23 17:44:20.255302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224e010e8eca'
down_revision = '2f348a93d2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
