"""Initial migration

Revision ID: 2f348a93d2cf
Revises: 
Create Date: 2024-07-23 12:32:44.505719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f348a93d2cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('use_type', sa.String(length=50), nullable=False),
    sa.Column('game_type', sa.String(length=50), nullable=True),
    sa.Column('league_category', sa.String(length=50), nullable=True),
    sa.Column('player1', sa.String(length=50), nullable=True),
    sa.Column('player1_is_member', sa.Boolean(), nullable=True),
    sa.Column('player2', sa.String(length=50), nullable=True),
    sa.Column('player2_is_member', sa.Boolean(), nullable=True),
    sa.Column('player3', sa.String(length=50), nullable=True),
    sa.Column('player3_is_member', sa.Boolean(), nullable=True),
    sa.Column('player4', sa.String(length=50), nullable=True),
    sa.Column('player4_is_member', sa.Boolean(), nullable=True),
    sa.Column('trainer', sa.String(length=50), nullable=True),
    sa.Column('elite_category', sa.String(length=50), nullable=True),
    sa.Column('academy_category', sa.String(length=50), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_name'))

    op.drop_table('court')
    # ### end Alembic commands ###
