"""Verificar migraciones

Revision ID: 55bf21c71ee0
Revises: 28b03dd549f4
Create Date: 2024-07-24 09:40:23.104514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bf21c71ee0'
down_revision = '28b03dd549f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
