"""Add is_member column to user table

Revision ID: a9b035e40f5a
Revises: b53720b6be22
Create Date: 2024-07-24 23:24:15.362004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b035e40f5a'
down_revision = 'b53720b6be22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
