"""Add is_member to User model

Revision ID: b53720b6be22
Revises: 55bf21c71ee0
Create Date: 2024-07-24 23:14:23.911219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53720b6be22'
down_revision = '55bf21c71ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_member', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_member')
    # ### end Alembic commands ###
