"""add is_member column to user again and new order in reserve

Revision ID: dbd05fb932cc
Revises: a9b035e40f5a
Create Date: 2024-07-25 01:06:41.756521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd05fb932cc'
down_revision = 'a9b035e40f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
